version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      "MYSQL_DATABASE": "iot"
      "MYSQL_ROOT_PASSWORD": "Pass@123"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
  mq:
    image: rabbitmq:3.8-management-alpine
    environment:
      "RABBITMQ_DEFAULT_USER": "admin"
      "RABBITMQ_DEFAULT_PASS": "admin"
      "RABBITMQ_DEFAULT_VHOST": "iot_dev"
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'